# Auto-generated using compose2nix v0.2.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."tautulli" = {
    image = "linuxserver/tautulli:2.13.4";
    environment = {
      "PGID" = "1080";
      "PUID" = "1080";
      "TZ" = "Europe/Amsterdam";
    };
    volumes = [
      "/Users/romanpeters/Developer/infrastructure_docker/tautulli/tautulli:/config:rw"
    ];
    ports = [
      "8009:8181/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=tautulli"
      "--network=tautulli_default"
    ];
  };
  systemd.services."podman-tautulli" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
    };
    after = [
      "podman-network-tautulli_default.service"
    ];
    requires = [
      "podman-network-tautulli_default.service"
    ];
    partOf = [
      "podman-compose-tautulli-root.target"
    ];
    wantedBy = [
      "podman-compose-tautulli-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-tautulli_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f tautulli_default";
    };
    script = ''
      podman network inspect tautulli_default || podman network create tautulli_default
    '';
    partOf = [ "podman-compose-tautulli-root.target" ];
    wantedBy = [ "podman-compose-tautulli-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-tautulli-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
