---
repos:
  - repo: local
    hooks:
      - id: generate-index
        name: Generate index
        entry: python3 write_index.py
        language: python
        additional_dependencies:
          - pyyaml

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.22.2
    hooks:
      - id: ansible-lint
        args: [--fix]
