---
repos:
  - repo: local
    hooks:
      - id: generate-port-list
        name: Generate port list
        entry: python3 list.py README.md
        language: python
        additional_dependencies:
          - pyyaml

      - id: generate-nix-config
        name: Run compose2nix
        entry: bash -c 'find . -name docker-compose.yml -execdir sh -c "compose2nix" \;'
        language: system
        types: [file]
        files: docker-compose.yml

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.22.2
    hooks:
      - id: ansible-lint
        args: [--exclude, .github]
