---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.10
    container_name: homepage_app
    environment:
      PUID: 1000
      PGID: 998
    ports:
      - 8012:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
