---
name: vaultwarden
services:
  vaultwarden:
    image: vaultwarden/server:1.30.1
    container_name: 'vaultwarden'
    environment:
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'true'
      SENDS_ALLOWED: 'true'
      LOG_FILE: /data/logs/bitwarden.log
      EXTENDED_LOGGING: 'false'
      LOG_LEVEL: 'warn'
    volumes:
      - ./data:/data
    ports:
      - '8004:80'
      - '3012:3012'  # websocket
    restart: unless-stopped
