# Auto-generated using compose2nix v0.2.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."nginx_proxy_manager" = {
    image = "jc21/nginx-proxy-manager:2.11.1";
    volumes = [
      "/Users/romanpeters/Developer/infrastructure_docker/nginx_proxy_manager/data:/data:rw"
      "/Users/romanpeters/Developer/infrastructure_docker/nginx_proxy_manager/letsencrypt:/etc/letsencrypt:rw"
    ];
    ports = [
      "8003:81/tcp"
      "80:80/tcp"
      "443:443/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--dns=1.0.0.1"
      "--dns=1.1.1.1"
      "--network-alias=nginx_proxy_manager"
      "--network=nginx_default"
    ];
  };
  systemd.services."podman-nginx_proxy_manager" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
    };
    after = [
      "podman-network-nginx_default.service"
    ];
    requires = [
      "podman-network-nginx_default.service"
    ];
    partOf = [
      "podman-compose-nginx-root.target"
    ];
    wantedBy = [
      "podman-compose-nginx-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-nginx_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f nginx_default";
    };
    script = ''
      podman network inspect nginx_default || podman network create nginx_default
    '';
    partOf = [ "podman-compose-nginx-root.target" ];
    wantedBy = [ "podman-compose-nginx-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-nginx-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
