---
services:
  homebox:
    image: ghcr.io/hay-kot/homebox:v0.10.3
    container_name: "homebox"
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - ./data/:/data/
    ports:
      - "8002:7745"
    restart: always
    labels:
      - homepage.group=Applications
      - homepage.name=Homebox
      - homepage.icon=homebox.png
      - homepage.href=https://homebox.romanpeters.nl/
