---
name: uptime
services:
  uptime_kuma:
    image: louislam/uptime-kuma:1.23.11
    container_name: uptime_kuma
    volumes:
      - ./data:/app/data
    ports:
      - "8007:3001"
    restart: always
