# Auto-generated using compose2nix v0.2.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."uptime_kuma" = {
    image = "louislam/uptime-kuma:1.23.11";
    volumes = [
      "/Users/romanpeters/Developer/infrastructure_docker/uptime_kuma/data:/app/data:rw"
    ];
    ports = [
      "8007:3001/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=uptime_kuma"
      "--network=uptime_default"
    ];
  };
  systemd.services."podman-uptime_kuma" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
    };
    after = [
      "podman-network-uptime_default.service"
    ];
    requires = [
      "podman-network-uptime_default.service"
    ];
    partOf = [
      "podman-compose-uptime-root.target"
    ];
    wantedBy = [
      "podman-compose-uptime-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-uptime_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f uptime_default";
    };
    script = ''
      podman network inspect uptime_default || podman network create uptime_default
    '';
    partOf = [ "podman-compose-uptime-root.target" ];
    wantedBy = [ "podman-compose-uptime-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-uptime-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
