---
services:
  changedetection:
    image: dgtlmoon/changedetection.io:0.45.12
    container_name: changedetection
    environment:
      - BASE_URL=https://change.romanpeters.nl
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true
    volumes:
      - ./data:/datastore
    ports:
      - "8001:5000"
    depends_on:
      playwright-chrome:
        condition: service_started
    restart: always

  playwright-chrome:
    hostname: playwright-chrome
    image: browserless/chrome
    container_name: changedetection.io-browser
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=false
      - PREBOOT_CHROME=true
      - CONNECTION_TIMEOUT=300000
      - MAX_CONCURRENT_SESSIONS=10
      - CHROME_REFRESH_TIME=600000
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_STEALTH=true
    restart: unless-stopped
