---
services:
  heimdall:
    container_name: heimdall_rtv
    image: linuxserver/heimdall:2.5.8
    environment:
      - APP_NAME=RomanTV
    volumes:
      - ./heimdall:/config
    ports:
      - 8008:80
    restart: unless-stopped
    labels:
      - homepage.group=RomanTV
      - homepage.name=Landing Page
      - homepage.icon=heimdall.png
      - homepage.href=https://rtv.romanpeters.nl/
