---
services:
  adguardhome:
    image: adguard/adguardhome:v0.107.43
    container_name: adguard
    ports:
      - 8005:80/tcp
      - 53:53/udp
      - 53:53/tcp
      - 784:784/udp
      - 853:853/tcp
      - 3003:3000/tcp
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    restart: always
