# Auto-generated using compose2nix v0.2.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."adguard" = {
    image = "adguard/adguardhome:v0.107.43";
    volumes = [
      "/Users/romanpeters/Developer/infrastructure_docker/adguardhome/conf:/opt/adguardhome/conf:rw"
      "/Users/romanpeters/Developer/infrastructure_docker/adguardhome/work:/opt/adguardhome/work:rw"
    ];
    ports = [
      "8005:80/tcp"
      "53:53/udp"
      "53:53/tcp"
      "784:784/udp"
      "853:853/tcp"
      "3003:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=adguardhome"
      "--network=adguard_default"
    ];
  };
  systemd.services."podman-adguard" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
    };
    after = [
      "podman-network-adguard_default.service"
    ];
    requires = [
      "podman-network-adguard_default.service"
    ];
    partOf = [
      "podman-compose-adguard-root.target"
    ];
    wantedBy = [
      "podman-compose-adguard-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-adguard_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f adguard_default";
    };
    script = ''
      podman network inspect adguard_default || podman network create adguard_default
    '';
    partOf = [ "podman-compose-adguard-root.target" ];
    wantedBy = [ "podman-compose-adguard-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-adguard-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
