---
services:
  overseerr:
    image: sctx/overseerr:1.33.2
    container_name: overseerr
    ports:
      - 8010:5055
    volumes:
      - ./config/:/app/config
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    labels:
      - homepage.group=RomanTV
      - homepage.name=Overseerr
      - homepage.icon=overseerr.png
      - homepage.href=https://request.romanpeters.nl/
