# Auto-generated using compose2nix v0.2.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."heimdall_hello" = {
    image = "linuxserver/heimdall:2.5.8";
    environment = {
      "APP_NAME" = "romanpeters";
    };
    volumes = [
      "/Users/romanpeters/Developer/infrastructure_docker/heimdall_hello/heimdall:/config:rw"
    ];
    ports = [
      "8006:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=heimdall"
      "--network=hello_default"
    ];
  };
  systemd.services."podman-heimdall_hello" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
    };
    after = [
      "podman-network-hello_default.service"
    ];
    requires = [
      "podman-network-hello_default.service"
    ];
    partOf = [
      "podman-compose-hello-root.target"
    ];
    wantedBy = [
      "podman-compose-hello-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-hello_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f hello_default";
    };
    script = ''
      podman network inspect hello_default || podman network create hello_default
    '';
    partOf = [ "podman-compose-hello-root.target" ];
    wantedBy = [ "podman-compose-hello-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-hello-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
